<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">

    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/pygment_trac.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/print.css" media="print">

    <title>Website-maintenance-mode by jcgallaher</title>
  </head>

  <body>

    <header>
      <div class="container">
        <h1>Website-maintenance-mode</h1>
        <h2>Website Maintenance Mode allows you to easily and quickly put your website into maintenance mode via an Apache htaccess script</h2>

        <section id="downloads">
          <a href="https://github.com/jcgallaher/website-maintenance-mode/zipball/master" class="btn">Download as .zip</a>
          <a href="https://github.com/jcgallaher/website-maintenance-mode/tarball/master" class="btn">Download as .tar.gz</a>
          <a href="https://github.com/jcgallaher/website-maintenance-mode" class="btn btn-github"><span class="icon"></span>View on GitHub</a>
        </section>
      </div>
    </header>

    <div class="container">
      <section id="main_content">
        <h1>
<a id="website-maintenance-mode" class="anchor" href="#website-maintenance-mode" aria-hidden="true"><span class="octicon octicon-link"></span></a>Website Maintenance Mode</h1>

<p>The Website Maintenance Mode allows you to easily and quickly put your website into maintenance mode via an Apache htaccess script and temporarily 302 redirect all incoming visitors *<em>accept for the computer you're working on by an IP address exception</em> to a custom maintenance page that states the website is down for maintenance work.</p>

<p><em>Note:</em> The IP address exception allows only you to view, edit, and test any changes you make your website without being rerouted to the maintenance page. By having this exception you can ensure that everything on your live site is working correctly before returning your website to it's normal viewing mode.</p>

<h3>
<a id="requirements-for-using-the-maintenance-mode" class="anchor" href="#requirements-for-using-the-maintenance-mode" aria-hidden="true"><span class="octicon octicon-link"></span></a>Requirements for using the Maintenance Mode</h3>

<p>To use these scripts you will need an Apache based web server, FTP access to the server, and a basic text editor thats installed on the computer you're using. SSH access is helpful, but not required.</p>

<h2>
<a id="quick-setup-and-start" class="anchor" href="#quick-setup-and-start" aria-hidden="true"><span class="octicon octicon-link"></span></a>Quick Setup and Start</h2>

<p>Setting up the Maintenance Mode is fairly quick, simple and straight forward. If you're not too familiar with working with .htaccess files, this quick start guide should be enough to get you started fairly quickly. </p>

<ol>
<li>
<p>Upload the files (Psst...Don't worry the .htaccess file is already commented out (turned off) so you don't throw your site into maintenance mode as soon as the file is uploaded to the server.</p>

<ol>
<li><p><strong>If you don't have an .htaccess file for your site</strong>, upload all the files (.htaccess, maintenance.html, and maintenance.css to the root directory of your website.</p></li>
<li><p><strong>If you already do have an .htacess file for your site</strong> upload the maintenance.html and maintenance.css files to the root of your website and copy n' paste the Website Maintenance Mode script into your current .htaccess file. </p></li>
</ol>
</li>
<li>
<p>Setup an IP Address exception so while the site is in maintenance mode you'll still be able to see and test any changes you make to the site. Open the .htaccess file, go the line <strong>#RewriteCond %{REMOTE_ADDR} !^255.255.255.255$</strong> and change the default IP address <strong>255.255.255.255</strong> to your IP address.</p>

<ol>
<li><p><em>Note:</em> If you're connected to a router, the IP address will be the one assigned to the router, not the internal IP that your router assigns to your computer. If you don't know what your IP address is, do a quick Internet search for "What's my IP address?" with your favorite search engine and the search results should provide you with your current IP address either within the search results or give you a list of sites that will display it for you.</p></li>
<li><p>Also, keep in mind that any computers connected to that very same router will also have the same outside IP address and therefore they will not be re-routed to the maintenance page. This may or may not be a concern for you depending on your situation. To better clarify, if you're connected to a wifi hotspot at a coffee shop or any place that offers wifi, any computers that are connected to that same hot spot will have the same IP address and thus will not be redirected to the web site's maintenance page.</p></li>
<li><p>Lastly keep in mind that your IP address may change from time to time even if you work from the same location with the same internet connection. Double check your IP address before putting your website into maintenance mode so you don't get redirected to the maintenance page.</p></li>
</ol>
</li>
<li><p>To put the website into maintenance mode and redirect all incoming visitors to the maintenance notice, just <strong>uncomment</strong> the lines in the .htaccess file starting with <strong></strong> through (and including) <strong></strong> using your favorite text editor on the server and save the file to make those changes.</p></li>
</ol>

<p><em>Note:</em> If you have SSH access and text editor installed on the server (Nano, Vim, etc.) you can edit the .htaccess file directly on the server instead of having to edit the file locally, save it, and upload it every time you need to take the website in and out of maintenance mode. </p>

<ol>
<li>When you're ready to take the website out of maintenance mode, simply go back and <strong>re-comment</strong> the lines <strong></strong> through (and including) <strong></strong> and save the file to make those changes.</li>
</ol>

<h3>
<a id="included-files" class="anchor" href="#included-files" aria-hidden="true"><span class="octicon octicon-link"></span></a>Included Files</h3>

<p>The maintenance consists of the following files:</p>

<p>.htaccess - The main script for redirecting the website viewers to the maintenance page. By default all lines in the script are commented out (turned off) in order to prevent the htaccess file from putting the website into maintenance mode right after upload.</p>

<p>maintenance.html - An extremely simple mobile friendly HTML5 based document that states "Our website is currently undergoing maintenance."</p>

<p>maintenance.css - A simple CSS file which controls the look of the maintenance.html page. resets all browser styles, provides an orange background color for the page, centers the message, sets the font family to sans-serif,.</p>

<h3>
<a id="htaccess-file-in-detail" class="anchor" href="#htaccess-file-in-detail" aria-hidden="true"><span class="octicon octicon-link"></span></a>.htaccess file in detail</h3>

<p>When you first view the .htaccess file, every line in the file will be commented out (maintenance mode will be turned off) as you can see in the following below.</p>

<pre><code>## Website Maintenance Mode (Uncomment all lines from &lt;IfModule mod_rewrite.c&gt; through (and including) &lt;/IfModule&gt; to activate. Re-comment those lines with a # to turn off maintenance mode)
## NOTE: You must update REMOTE_ADDR with your current IP address to view changes and preform testing.
############################################################################################################################################

#&lt;IfModule mod_rewrite.c&gt;
 #RewriteEngine on 
 #RewriteCond %{REMOTE_ADDR} !^255\.255\.255\.255$
 #RewriteCond %{REQUEST_URI} !/maintenance.html$ [NC]
 #RewriteCond %{REQUEST_URI} !\.(jpe?g?|png|gif|svg|css|js) [NC]
 #RewriteRule .* /maintenance.html [R=302,L]
#&lt;/IfModule&gt;
</code></pre>

<h4>
<a id="breakdown-of-some-of-htaccess-script-lines" class="anchor" href="#breakdown-of-some-of-htaccess-script-lines" aria-hidden="true"><span class="octicon octicon-link"></span></a>Breakdown of some of .htaccess script lines</h4>

<p>The following lines might be of interest to you, if you wish to customize the .htaccess file. <em>Note: Making changes to the .htaccess file can cause your site to become un-viewable if you make a syntax error in the file.</em></p>

<p><code>RewriteCond %{REMOTE_ADDR} !^255\.255\.255\.255$</code> This line sets the IP address exception for your computer.</p>

<p><code>RewriteCond %{REQUEST_URI} !/maintenance.html$ [NC]</code> This line sets the condition for maintenance.html</p>

<p><em>Note: If you would like to modify the redirect page to a different page, make sure to make the change in both the RewriteCond %{REQUEST_URI} !/maintenance.html$ [NC] and RewriteRule .</em> <em>/maintenance.html [R=302,L] lines</em></p>

<p><code>RewriteCond %{REQUEST_URI} !\.(jpe?g?|png|gif|svg|css|js) [NC]</code> This line allows what types of files can be displayed in the redirect page. (Currently it is set to allow the following types of file extensions: .jpeg, .png, .gif, .svg, .css, and .js)</p>

<p><code>RewriteRule .* /maintenance.html [R=302,L]</code> This line redirects all visitors to maintenance.html and is set as a 302 temporary redirect.</p>

<h3>
<a id="maintenancehtml-file-in-detail" class="anchor" href="#maintenancehtml-file-in-detail" aria-hidden="true"><span class="octicon octicon-link"></span></a>maintenance.html file in detail</h3>

<p>The maintenance.html file is very minimal so you can customize it fairly quickly without having to deal with excessive code.</p>

<pre><code>&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta http-equiv="content-type" content="text/html; charset=utf-8" /&gt;
&lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
    &lt;link rel="stylesheet" type="text/css" href="maintenance.css" media="screen" /&gt;
&lt;title&gt;Our website is currently undergoing maintenance&lt;/title&gt;
&lt;/head&gt;
    &lt;body&gt;
        &lt;h1&gt;Our website is currently undergoing maintenance.&lt;/h1&gt;
    &lt;/body&gt;
&lt;/html&gt;
</code></pre>

<p>The following lines might be of interest to you, if you want to customize the maintenance.html file.</p>

<p><code>&lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;</code> This is a mobile friendly tag line that optimizes the page based on the width of the device.</p>

<p><code>&lt;link rel="stylesheet" type="text/css" href="maintenance.css" media="screen" /&gt;</code> This is the link for the maintenance.css file. For simplicity and compatibility reasons the maintenance.css is set to the root directory (same directory) as the maintenance.html file. Also, the css file is set to screen viewing only.</p>

<p><code>&lt;title&gt;Our website is currently undergoing maintenance&lt;/title&gt;</code> The default maintenance page title.</p>

<p><code>&lt;h1&gt;Our website is currently undergoing maintenance.&lt;/h1&gt;</code> Between the body tags, the message that all viewers will see is set with h1 tags.</p>

<h3>
<a id="maintenancecss-file-in-detail" class="anchor" href="#maintenancecss-file-in-detail" aria-hidden="true"><span class="octicon octicon-link"></span></a>maintenance.css file in detail</h3>

<p>The maintenance.css file provides styles for the maintenance.html file. The css file is split into two sections:</p>

<ol>
<li><p>Browser reset style rules (written by Eric Meyer) to eliminate any conflicting browser styles. (I suggest keeping this code intact)</p></li>
<li><p>Maintenance mode styles section (written by myself) provides styling for the background and the h1 tag.</p></li>
</ol>

<p><em>Note: Eric Meyer's Reset Styles section has been omitted in the code example below</em></p>

<pre><code>body {
    background-color: #ff5800;
}

h1 {
    text-align: center;
    margin: 0;
    padding: 1em 0 0 0;
    color: #e0e6e6;
    font-family: arial, sans-serif;
    font-size: 3em;
}
</code></pre>

<p>The following lines might be of interest to you, if you want to customize the maintenance.css file.
<em>Note:</em> Em values were used were necessary instead of pixel values in order to provide a more mobile friendly page across different screen sizes.</p>

<p><code>body { background-color: #ff5800; }</code> This style rule defines the background color for the maintenance.html page. By default it is set to a bright shade of orange using a hexadecimal color.</p>

<p><em>Note:</em> h1 tag rules will be explained separately for better clarity.</p>

<p><code>text-align: center;</code> This style centers the text on the screen regardless of screen size.</p>

<p><code>margin: 0;</code> The margin rule is set to a zero margin on all sides.</p>

<p><code>padding: 1em 0 0 0;</code> The padding rule adds 1em of padding to the top of the screen in order to push down the heading somewhat. (Right, bottom, and left are set to zero)</p>

<p><code>color: #e0e6e6;</code> The font heading color is set to a light Grey.</p>

<p><code>font-family: arial, sans-serif;</code> The heading typeface is set to display in arial first and then sans-serif if the viewer doesn't have arial installed on their computer.</p>

<p><code>font-size: 3em;</code> The size of the typeface is set to 3em.</p>
      </section>
    </div>

    
  </body>
</html>